import { inter } from '@/app/ui/fonts' ;
import Header from '@/app/components/Header' ;
import './globals.css' ;

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
